spring:
    r2dbc:
        urL: r2dbc:postgresql://localhost:5433/anime
        username: root
        password: root

logging:
    level:
        org:
            springframework:
                data:
                    r2dbc: DEBUG